spring.application.name=practice

spring.datasource.url=jdbc:postgresql://localhost/practicedb
spring.datasource.username=postgres
spring.datasource.password=Rathish@123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=Rathish
spring.security.user.password=1234